- name: Put Nginx configuration files
  template: 
    src: "{{ role_path }}/templates/nginx/{{ item }}.conf.j2"
    dest: "{{ nginx.conf_dir }}/{{ item }}.conf"
  with_items:
    - nginx
    - octoprint
- name: Start Nginx container
  docker_container:
    name: nginx
    image: nginx:mainline-alpine
    pull: yes
    recreate: yes
    restart_policy: always
    user: "root:root"
    networks:
      - name: "{{ octoprint.network }}"
    published_ports:
      - "80:80"
      - "443:443"
    env:
      TZ: "{{ common.timezone }}"
    volumes:
      - "/opt/nginx/conf/:/etc/nginx/:ro"
      - "/tmp/nginx/cache/:/var/lib/nginx/cache:rw"
      - "/tmp/rpi_cam/:/tmp/rpi_cam/:ro"