- name: Install Octoprint container
  docker_container:
    name: octoprint
    image: nunofgs/octoprint:1.3.9
    pull: yes
    restart_policy: always
    network_mode: host
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0:rw
    published_ports:
      - "5000:5000"
    env:
      TZ: "{{ common.timezone }}"