- name: Create Octoprint group
  group:
    name: "{{ secrets.octoprint.group_name }}"
    gid: "{{ secrets.octoprint.gid }}"
- name: Create Octoprint user
  user:
    name: "{{ secrets.octoprint.user_name }}"
    comment: Octoprint user
    uid: "{{ secrets.octoprint.uid }}"
    group: "{{ secrets.octoprint.group_name }}"
    update_password: always
    create_home: no
- name: Install Octoprint container
  docker_container:
    name: octoprint
    image: chudsaviet/octoprint-docker-light:latest
    pull: yes
    restart_policy: always
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0:rw
    networks:
      - name: "{{ octoprint.network }}"
    user: "{{ secrets.octoprint.uid }}:{{ secrets.octoprint.gid }}"
    env:
      TZ: "{{ common.timezone }}"