- hosts: god
  vars_files:
    - secrets.yml
  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'chest', tags: 'chest'}
    - {role: 'home_assistant', tags: 'home_assistant'}
    - {role: 'home_portal', tags: 'home_portal'}