- name: Create Mongodb group
  group:
    name: "{{ secrets.mongodb.group_name }}"
    gid: "{{ secrets.mongodb.gid }}"
- name: Create Mongodb user
  user:
    name: "{{ secrets.mongodb.user_name }}"
    comment: Mongodb user
    uid: "{{ secrets.mongodb.uid }}"
    group: "{{ secrets.mongodb.group_name }}"
    update_password: always
    create_home: no
- name: Start Mongodb container
  docker_container:
    name: mongodb
    image: bitnami/mongodb:4.2
    pull: yes
    recreate: yes
    restart_policy: always
    user: "{{ secrets.mongodb.uid }}:{{ secrets.mongodb.gid }}"
    published_ports:
      - "{{ secrets.mongodb.port }}:8081"
    env:
      TZ: "{{ common.timezone }}"
      MONGO_INITDB_ROOT_USERNAME: "{{ secrets.mongodb.root_username }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ secrets.mongodb.root_password }}"
    volumes:
      - "/opt/mongodb:/bitnami:rw"