- name: Install sources.list for Apt
  template:
    src: "templates/{{ ansible_lsb.id }}.sources.list.j2"
    dest: /etc/apt/sources.list
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes
- name: Install common APT and pip packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip