- name: Install msmtp MTA
  apt:
    name:
      - msmtp
      - msmtp-mta
      - s-nail
    update_cache: yes
- name: Put msmtp MTA config file
  template:
    src: "templates/msmtprc.j2"
    dest: "/etc/msmtprc"