- name: Set timezone
  timezone:
    hwclock: UTC
    name: "{{ common.timezone }}"
- name: Remove ntpd (package 'ntp')
  apt:
    name: ntp
    state: absent
    update_cache: yes
- name: Install chrony
  apt:
    name: chrony
    update_cache: yes
- name: Put chrony config file
  template:
    src: "templates/chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
- name: Restart chrony
  service:
    name: chrony
    enabled: yes
    state: restarted