---
ansible_host: "{{ secrets.aldan.host }}"
ansible_port: "{{ secrets.aldan.ssh_port }}"
ansible_user: "{{ secrets.aldan.user_name }}"
ansible_become: true
ansible_become_pass: "{{ secrets.aldan.user_password }}"
host_arch: amd64
chest_uuid: "{{ secrets.chest.uuid }}"