---
- name: Install mdadm
  apt:
    name: mdadm
    update_cache: yes
- name: Put mdadm config
  template:
    src: "{{ role_path }}/files/mdadm.conf.j2"
    dest: "/etc/mdadm/mdadm.conf"
- name: Update initramfs
  command: update-initramfs -u
- name: Enable and restart mdadm service
  service:
    name: mdmonitor
    enabled: yes
    state: restarted
- name: Creates a cron entry to check all RAID arrays on a schedule
  template:
    src: "{{ role_path }}/files/cron_mdadm.j2"
    dest: "/etc/cron.d/mdadm"
- name: Enable and restart cron
  service:
    name: cron
    enabled: yes
    state: restarted
- name: Create 'chest' mountpoint
  file:
    path: "{{ chest.local_path }}"
    state: directory
    mode: "a+rwx"
- name: Mount 'chest' partition
  mount:
    path: "{{ chest.local_path }}"
    src: UUID="{{ chest_uuid }}"
    fstype: ext4
    opts: noatime
    state: mounted


 