- name: Install Samba server container
  docker_container:
    name: samba_share
    image: chudsaviet/samba
    pull: yes
    restart_policy: always
    network_mode: host
    env:
      TZ: "{{ common.timezone }}"
    volumes:
      - "{{ chest.local_path }}:{{ chest.local_path }}:rw"
    command:
      - samba.sh
      - -s "chest;{{ chest.local_path }};yes;no;no;{{ secrets.samba.shared_user }}"
      - -s "{{ timecapsule.share_name }};{{ timecapsule.local_path }};yes;no;no;{{ secrets.samba.tc_user }}"
      - -u "{{ secrets.samba.tc_user }};{{ secrets.samba.tc_password }}"
      - -u "{{ secrets.samba.shared_user }};{{ secrets.samba.shared_password }}"